\context ChordNames
	\chords {
		\set chordChanges = ##t
		% intro
		a2.:m e2.:m b2.:7 e4.:m e4.:7
		a2.:m e2.:m b2.:7 e2.:m

		% ay, que pena...
		e4.:m b4.:7 e2.:m c2. b2.:7
		b2.:7 e2.:m c4. a4.:m7 b2.:7
		b2.:7 e2.:m c4. b4.:7 e2.:m

		% ay, que pena...
		e4.:m b4.:7 e2.:m c2. b2.:7
		b2.:7 e2.:m c4. a4.:m7 b2.:7
		b2.:7 e2.:m c4. b4.:7 e2.:m

		% pero que importa...
		d2.:7 g2. d2.:7 g2.
		b2.:7 e2.:m b2.:7 e4.:m e4.:7
		a2.:m e2.:m b2.:7 e2.:m

		% pero que importa...
		d2.:7 g2. d2.:7 g2.
		b2.:7 e2.:m b2.:7 e4.:m e4.:7
		a2.:m e2.:m b2.:7 e2.:m

		% pena, que pena...
		b2.:7 e2.:m b2.:7 e4.:m e4.:7
		a2.:m e2.:m b2.:7 e2.:m
		a2.:m e2.:m b2.:7 e2.:m e2.:m
	}
